### ISSUE TITLE
Could you please direct me or provide me with a flowchart so that I can follow your site and learn from it gradually?

### ISSUE THREAD

**Issue by MdAshrafulAlam** [WesleyyC/wesleyyc.github.io#2]
I want to form a personal site for academic use. I found your GitHub page on the internet. This one has attracted me a lot. Could you please help me out to learn and build up mine one?

**Comment by MdAshrafulAlam** [comment]
I want to form a personal site for academic use. I found your GitHub page on the internet. This one has attracted me a lot. Could you please help me out to learn and build up mine one?

**Comment by WesleyyC** [comment]
You can start from [here](https://medium.com/thoughts-and-notes/tool-build-a-personal-website-using-jekyll-blog-framework-7fd49c43be42), but there are probably other great tutorial as well. Jekyll is pretty easy to use and low maintenance in general.
